class CurrencyInfo {
  final String code;
  final String name;
  final String flag;

  const CurrencyInfo(this.code, this.name, this.flag);

  String get fullName => '$name ($code)';
  String get shortName => code;
}

const Map<String, CurrencyInfo> currencyDetails = {
  'USD': CurrencyInfo('USD', 'United States Dollar', '🇺🇸'),
  'EUR': CurrencyInfo('EUR', 'Euro', '🇪🇺'),
  'GBP': CurrencyInfo('GBP', 'British Pound', '🇬🇧'),
  'INR': CurrencyInfo('INR', 'Indian Rupee', '🇮🇳'),
  'JPY': CurrencyInfo('JPY', 'Japanese Yen', '🇯🇵'),
  'CAD': CurrencyInfo('CAD', 'Canadian Dollar', '🇨🇦'),
  'AUD': CurrencyInfo('AUD', 'Australian Dollar', '🇦🇺'),
  'SGD': CurrencyInfo('SGD', 'Singapore Dollar', '🇸🇬'),
  'CHF': CurrencyInfo('CHF', 'Swiss Franc', '🇨🇭'),
  'CNY': CurrencyInfo('CNY', 'Chinese Yuan', '🇨🇳'),
  'NZD': CurrencyInfo('NZD', 'New Zealand Dollar', '🇳🇿'),
  'ZAR': CurrencyInfo('ZAR', 'South African Rand', '🇿🇦'),
  'AED': CurrencyInfo('AED', 'United Arab Emirates Dirham', '🇦🇪'),
  'AFN': CurrencyInfo('AFN', 'Afghan Afghani', '🇦🇫'),
  'ALL': CurrencyInfo('ALL', 'Albanian Lek', '🇦🇱'),
  'AMD': CurrencyInfo('AMD', 'Armenian Dram', '🇦🇲'),
  'ANG': CurrencyInfo('ANG', 'Netherlands Antillean Guilder', '🇨🇼'),
  'AOA': CurrencyInfo('AOA', 'Angolan Kwanza', '🇦🇴'),
  'ARS': CurrencyInfo('ARS', 'Argentine Peso', '🇦🇷'),
  'AWG': CurrencyInfo('AWG', 'Aruban Florin', '🇦🇼'),
  'AZN': CurrencyInfo('AZN', 'Azerbaijani Manat', '🇦🇿'),
  'BAM': CurrencyInfo('BAM', 'Bosnia-Herzegovina Convertible Mark', '🇧🇦'),
  'BBD': CurrencyInfo('BBD', 'Barbadian Dollar', '🇧🇧'),
  'BDT': CurrencyInfo('BDT', 'Bangladeshi Taka', '🇧🇩'),
  'BGN': CurrencyInfo('BGN', 'Bulgarian Lev', '🇧🇬'),
  'BHD': CurrencyInfo('BHD', 'Bahraini Dinar', '🇧🇭'),
  'BIF': CurrencyInfo('BIF', 'Burundian Franc', '🇧🇮'),
  'BMD': CurrencyInfo('BMD', 'Bermudan Dollar', '🇧🇲'),
  'BND': CurrencyInfo('BND', 'Brunei Dollar', '🇧🇳'),
  'BOB': CurrencyInfo('BOB', 'Bolivian Boliviano', '🇧🇴'),
  'BRL': CurrencyInfo('BRL', 'Brazilian Real', '🇧🇷'),
  'BSD': CurrencyInfo('BSD', 'Bahamian Dollar', '🇧🇸'),
  'BTN': CurrencyInfo('BTN', 'Bhutanese Ngultrum', '🇧🇹'),
  'BWP': CurrencyInfo('BWP', 'Botswanan Pula', '🇧🇼'),
  'BYN': CurrencyInfo('BYN', 'Belarusian Ruble', '🇧🇾'),
  'BZD': CurrencyInfo('BZD', 'Belize Dollar', '🇧🇿'),
  'CDF': CurrencyInfo('CDF', 'Congolese Franc', '🇨🇩'),
  'CLP': CurrencyInfo('CLP', 'Chilean Peso', '🇨🇱'),
  'COP': CurrencyInfo('COP', 'Colombian Peso', '🇨🇴'),
  'CRC': CurrencyInfo('CRC', 'Costa Rican Colón', '🇨🇷'),
  'CUP': CurrencyInfo('CUP', 'Cuban Peso', '🇨🇺'),
  'CVE': CurrencyInfo('CVE', 'Cape Verdean Escudo', '🇨🇻'),
  'CZK': CurrencyInfo('CZK', 'Czech Koruna', '🇨🇿'),
  'DJF': CurrencyInfo('DJF', 'Djiboutian Franc', '🇩🇯'),
  'DKK': CurrencyInfo('DKK', 'Danish Krone', '🇩🇰'),
  'DOP': CurrencyInfo('DOP', 'Dominican Peso', '🇩🇴'),
  'DZD': CurrencyInfo('DZD', 'Algerian Dinar', '🇩🇿'),
  'EGP': CurrencyInfo('EGP', 'Egyptian Pound', '🇪🇬'),
  'ERN': CurrencyInfo('ERN', 'Eritrean Nakfa', '🇪🇷'),
  'ETB': CurrencyInfo('ETB', 'Ethiopian Birr', '🇪🇹'),
  'FJD': CurrencyInfo('FJD', 'Fijian Dollar', '🇫🇯'),
  'FKP': CurrencyInfo('FKP', 'Falkland Islands Pound', '🇫🇰'),
  'FOK': CurrencyInfo('FOK', 'Faroese Króna', '🇫🇴'),
  'GEL': CurrencyInfo('GEL', 'Georgian Lari', '🇬🇪'),
  'GGP': CurrencyInfo('GGP', 'Guernsey Pound', '🇬🇬'),
  'GHS': CurrencyInfo('GHS', 'Ghanaian Cedi', '🇬🇭'),
  'GIP': CurrencyInfo('GIP', 'Gibraltar Pound', '🇬🇮'),
  'GMD': CurrencyInfo('GMD', 'Gambian Dalasi', '🇬🇲'),
  'GNF': CurrencyInfo('GNF', 'Guinean Franc', '🇬🇳'),
  'GTQ': CurrencyInfo('GTQ', 'Guatemalan Quetzal', '🇬🇹'),
  'GYD': CurrencyInfo('GYD', 'Guyanaese Dollar', '🇬🇾'),
  'HKD': CurrencyInfo('HKD', 'Hong Kong Dollar', '🇭🇰'),
  'HNL': CurrencyInfo('HNL', 'Honduran Lempira', '🇭🇳'),
  'HRK': CurrencyInfo('HRK', 'Croatian Kuna', '🇭🇷'),
  'HTG': CurrencyInfo('HTG', 'Haitian Gourde', '🇭🇹'),
  'HUF': CurrencyInfo('HUF', 'Hungarian Forint', '🇭🇺'),
  'IDR': CurrencyInfo('IDR', 'Indonesian Rupiah', '🇮🇩'),
  'ILS': CurrencyInfo('ILS', 'Israeli New Shekel', '🇮🇱'),
  'IMP': CurrencyInfo('IMP', 'Isle of Man Pound', '🇮🇲'),
  'IQD': CurrencyInfo('IQD', 'Iraqi Dinar', '🇮🇶'),
  'IRR': CurrencyInfo('IRR', 'Iranian Rial', '🇮🇷'),
  'ISK': CurrencyInfo('ISK', 'Icelandic Króna', '🇮🇸'),
  'JEP': CurrencyInfo('JEP', 'Jersey Pound', '🇯🇪'),
  'JMD': CurrencyInfo('JMD', 'Jamaican Dollar', '🇯🇲'),
  'JOD': CurrencyInfo('JOD', 'Jordanian Dinar', '🇯🇴'),
  'KES': CurrencyInfo('KES', 'Kenyan Shilling', '🇰🇪'),
  'KGS': CurrencyInfo('KGS', 'Kyrgystani Som', '🇰🇬'),
  'KHR': CurrencyInfo('KHR', 'Cambodian Riel', '🇰🇭'),
  'KID': CurrencyInfo('KID', 'Kiribati Dollar', '🇰🇮'),
  'KMF': CurrencyInfo('KMF', 'Comorian Franc', '🇰🇲'),
  'KRW': CurrencyInfo('KRW', 'South Korean Won', '🇰🇷'),
  'KWD': CurrencyInfo('KWD', 'Kuwaiti Dinar', '🇰🇼'),
  'KYD': CurrencyInfo('KYD', 'Cayman Islands Dollar', '🇰🇾'),
  'KZT': CurrencyInfo('KZT', 'Kazakhstani Tenge', '🇰🇿'),
  'LAK': CurrencyInfo('LAK', 'Laotian Kip', '🇱🇦'),
  'LBP': CurrencyInfo('LBP', 'Lebanese Pound', '🇱🇧'),
  'LKR': CurrencyInfo('LKR', 'Sri Lankan Rupee', '🇱🇰'),
  'LRD': CurrencyInfo('LRD', 'Liberian Dollar', '🇱🇷'),
  'LSL': CurrencyInfo('LSL', 'Lesotho Loti', '🇱🇸'),
  'LYD': CurrencyInfo('LYD', 'Libyan Dinar', '🇱🇾'),
  'MAD': CurrencyInfo('MAD', 'Moroccan Dirham', '🇲🇦'),
  'MDL': CurrencyInfo('MDL', 'Moldovan Leu', '🇲🇩'),
  'MGA': CurrencyInfo('MGA', 'Malagasy Ariary', '🇲🇬'),
  'MKD': CurrencyInfo('MKD', 'Macedonian Denar', '🇲🇰'),
  'MMK': CurrencyInfo('MMK', 'Myanmar Kyat', '🇲🇲'),
  'MNT': CurrencyInfo('MNT', 'Mongolian Tugrik', '🇲🇳'),
  'MOP': CurrencyInfo('MOP', 'Macanese Pataca', '🇲🇴'),
  'MRU': CurrencyInfo('MRU', 'Mauritanian Ouguiya', '🇲🇷'),
  'MUR': CurrencyInfo('MUR', 'Mauritian Rupee', '🇲🇺'),
  'MVR': CurrencyInfo('MVR', 'Maldivian Rufiyaa', '🇲🇻'),
  'MWK': CurrencyInfo('MWK', 'Malawian Kwacha', '🇲🇼'),
  'MXN': CurrencyInfo('MXN', 'Mexican Peso', '🇲🇽'),
  'MYR': CurrencyInfo('MYR', 'Malaysian Ringgit', '🇲🇾'),
  'MZN': CurrencyInfo('MZN', 'Mozambican Metical', '🇲🇿'),
  'NAD': CurrencyInfo('NAD', 'Namibian Dollar', '🇳🇦'),
  'NGN': CurrencyInfo('NGN', 'Nigerian Naira', '🇳🇬'),
  'NIO': CurrencyInfo('NIO', 'Nicaraguan Córdoba', '🇳🇮'),
  'NOK': CurrencyInfo('NOK', 'Norwegian Krone', '🇳🇴'),
  'NPR': CurrencyInfo('NPR', 'Nepalese Rupee', '🇳🇵'),
  'OMR': CurrencyInfo('OMR', 'Omani Rial', '🇴🇲'),
  'PAB': CurrencyInfo('PAB', 'Panamanian Balboa', '🇵🇦'),
  'PEN': CurrencyInfo('PEN', 'Peruvian Sol', '🇵🇪'),
  'PGK': CurrencyInfo('PGK', 'Papua New Guinean Kina', '🇵🇬'),
  'PHP': CurrencyInfo('PHP', 'Philippine Peso', '🇵🇭'),
  'PKR': CurrencyInfo('PKR', 'Pakistani Rupee', '🇵🇰'),
  'PLN': CurrencyInfo('PLN', 'Polish Zloty', '🇵🇱'),
  'PYG': CurrencyInfo('PYG', 'Paraguayan Guarani', '🇵🇾'),
  'QAR': CurrencyInfo('QAR', 'Qatari Rial', '🇶🇦'),
  'RON': CurrencyInfo('RON', 'Romanian Leu', '🇷🇴'),
  'RSD': CurrencyInfo('RSD', 'Serbian Dinar', '🇷🇸'),
  'RUB': CurrencyInfo('RUB', 'Russian Ruble', '🇷🇺'),
  'RWF': CurrencyInfo('RWF', 'Rwandan Franc', '🇷🇼'),
  'SAR': CurrencyInfo('SAR', 'Saudi Riyal', '🇸🇦'),
  'SBD': CurrencyInfo('SBD', 'Solomon Islands Dollar', '🇸🇧'),
  'SCR': CurrencyInfo('SCR', 'Seychellois Rupee', '🇸🇨'),
  'SDG': CurrencyInfo('SDG', 'Sudanese Pound', '🇸🇩'),
  'SEK': CurrencyInfo('SEK', 'Swedish Krona', '🇸🇪'),
  'SHP': CurrencyInfo('SHP', 'St. Helena Pound', '🇸🇭'),
  'SLL': CurrencyInfo('SLL', 'Sierra Leonean Leone', '🇸🇱'),
  'SOS': CurrencyInfo('SOS', 'Somali Shilling', '🇸🇴'),
  'SRD': CurrencyInfo('SRD', 'Surinamese Dollar', '🇸🇷'),
  'SSP': CurrencyInfo('SSP', 'South Sudanese Pound', '🇸🇸'),
  'STN': CurrencyInfo('STN', 'São Tomé & Príncipe Dobra', '🇸🇹'),
  'SYP': CurrencyInfo('SYP', 'Syrian Pound', '🇸🇾'),
  'SZL': CurrencyInfo('SZL', 'Swazi Lilangeni', '🇸🇿'),
  'THB': CurrencyInfo('THB', 'Thai Baht', '🇹🇭'),
  'TJS': CurrencyInfo('TJS', 'Tajikistani Somoni', '🇹🇯'),
  'TMT': CurrencyInfo('TMT', 'Turkmenistani Manat', '🇹🇲'),
  'TND': CurrencyInfo('TND', 'Tunisian Dinar', '🇹🇳'),
  'TOP': CurrencyInfo('TOP', 'Tongan Paʻanga', '🇹🇴'),
  'TRY': CurrencyInfo('TRY', 'Turkish Lira', '🇹🇷'),
  'TTD': CurrencyInfo('TTD', 'Trinidad & Tobago Dollar', '🇹🇹'),
  'TVD': CurrencyInfo('TVD', 'Tuvaluan Dollar', '🇹🇻'),
  'TWD': CurrencyInfo('TWD', 'New Taiwan Dollar', '🇹🇼'),
  'TZS': CurrencyInfo('TZS', 'Tanzanian Shilling', '🇹🇿'),
  'UAH': CurrencyInfo('UAH', 'Ukrainian Hryvnia', '🇺🇦'),
  'UGX': CurrencyInfo('UGX', 'Ugandan Shilling', '🇺🇬'),
  'UYU': CurrencyInfo('UYU', 'Uruguayan Peso', '🇺🇾'),
  'UZS': CurrencyInfo('UZS', 'Uzbekistani Som', '🇺🇿'),
  'VES': CurrencyInfo('VES', 'Venezuelan Bolívar', '🇻🇪'),
  'VND': CurrencyInfo('VND', 'Vietnamese Dong', '🇻🇳'),
  'VUV': CurrencyInfo('VUV', 'Vanuatu Vatu', '🇻🇺'),
  'WST': CurrencyInfo('WST', 'Samoan Tala', '🇼🇸'),
  'XAF': CurrencyInfo('XAF', 'Central African CFA Franc', '🇨🇲'),
  'XCD': CurrencyInfo('XCD', 'East Caribbean Dollar', '🇦🇬'),
  'XDR': CurrencyInfo('XDR', 'Special Drawing Rights', '🏦'),
  'XOF': CurrencyInfo('XOF', 'West African CFA Franc', '🇸🇳'),
  'XPF': CurrencyInfo('XPF', 'CFP Franc', '🇵🇫'),
  'YER': CurrencyInfo('YER', 'Yemeni Rial', '🇾🇪'),
  'ZMW': CurrencyInfo('ZMW', 'Zambian Kwacha', '🇿🇲'),
  'ZWL': CurrencyInfo('ZWL', 'Zimbabwean Dollar', '🇿🇼'),
};

CurrencyInfo getCurrencyInfo(String code) {
  return currencyDetails[code.toUpperCase()] ?? CurrencyInfo(code.toUpperCase(), 'Unknown Currency', '🏳️');
}
