/**
 * Shared design tokens. UI components live in each app for now (mobile uses
 * React Native primitives, web uses HTML), but the visual language is shared.
 */

const md3Light = {
  primary: '#315DA8',
  onPrimary: '#FFFFFF',
  primaryContainer: '#D7E3FF',
  onPrimaryContainer: '#001B3E',
  secondary: '#6B5F47',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#F4E3C2',
  onSecondaryContainer: '#241A04',
  tertiary: '#2F6B4F',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#B7F0CD',
  onTertiaryContainer: '#002113',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#410002',
  background: '#FBF8F3',
  onBackground: '#1B1B1F',
  surface: '#FBF8F3',
  onSurface: '#1B1B1F',
  surfaceVariant: '#E2E2EA',
  onSurfaceVariant: '#45464F',
  outline: '#747780',
  outlineVariant: '#C5C6D0',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#303034',
  inverseOnSurface: '#F2F0F4',
  inversePrimary: '#A9C7FF',
  surfaceDim: '#DBD9DD',
  surfaceBright: '#FBF8F3',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F5F2F7',
  surfaceContainer: '#EFEDF1',
  surfaceContainerHigh: '#E9E7EC',
  surfaceContainerHighest: '#E4E1E6',
};

const md3Dark = {
  primary: '#A9C7FF',
  onPrimary: '#00315F',
  primaryContainer: '#17497F',
  onPrimaryContainer: '#D7E3FF',
  secondary: '#DFC894',
  onSecondary: '#3B2F14',
  secondaryContainer: '#53462A',
  onSecondaryContainer: '#FCE4B2',
  tertiary: '#9BDDB5',
  onTertiary: '#003920',
  tertiaryContainer: '#0D5437',
  onTertiaryContainer: '#B7F0CD',
  error: '#FFB4AB',
  onError: '#690005',
  errorContainer: '#93000A',
  onErrorContainer: '#FFDAD6',
  background: '#111317',
  onBackground: '#E4E2E7',
  surface: '#111317',
  onSurface: '#E4E2E7',
  surfaceVariant: '#45464F',
  onSurfaceVariant: '#C5C6D0',
  outline: '#8F9099',
  outlineVariant: '#45464F',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#E4E2E7',
  inverseOnSurface: '#303034',
  inversePrimary: '#315DA8',
  surfaceDim: '#111317',
  surfaceBright: '#37393E',
  surfaceContainerLowest: '#0C0E12',
  surfaceContainerLow: '#191B20',
  surfaceContainer: '#1D2025',
  surfaceContainerHigh: '#282A2F',
  surfaceContainerHighest: '#33353A',
};

const finance = {
  positive: '#7DDC8A',
  onPositive: '#00390D',
  positiveContainer: '#0C4F22',
  onPositiveContainer: '#B9F5BB',
  warning: '#FFCF7A',
  onWarning: '#432C00',
  warningContainer: '#614100',
  onWarningContainer: '#FFE0A3',
  danger: md3Dark.error,
  onDanger: md3Dark.onError,
  transfer: '#95CCFF',
  onTransfer: '#003552',
  transferContainer: '#0D4C73',
  onTransferContainer: '#CBE6FF',
};

export const tokens = {
  color: {
    ink: '#0E1116',
    inkMuted: '#5A6470',
    bg: md3Light.background,
    surface: md3Light.surfaceContainerLowest,
    border: md3Light.outlineVariant,
    primary: md3Light.primary,
    positive: '#137A4B',
    warning: '#C77A00',
    overspend: md3Light.error,
    transferAccent: '#5D49C7',
    md3: {
      light: md3Light,
      dark: md3Dark,
    },
    finance,
    accountPalette: [
      '#4E7ECF',
      '#C56A5B',
      '#4B9A68',
      '#8A78D6',
      '#BD7B18',
      '#2D8C9F',
      '#B65B8E',
      '#7D8752',
    ],
    md3Bg: md3Dark.background,
    md3Surface: md3Dark.surfaceContainerLow,
    md3SurfaceHigh: md3Dark.surfaceContainerHigh,
    md3Outline: md3Dark.outlineVariant,
    md3Primary: md3Dark.primary,
    md3OnPrimary: md3Dark.onPrimary,
    md3Secondary: md3Dark.secondary,
    md3Positive: finance.positive,
    md3Danger: md3Dark.error,
  },
  radius: {
    xxs: 2,
    xs: 4,
    s: 6,
    sm: 8,
    m: 10,
    md: 12,
    l: 14,
    lg: 16,
    xl2: 24,
    xl: 28,
    pill: 999,
  },
  space: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 40,
  },
  font: {
    family: 'Inter, "Helvetica Neue", Arial, sans-serif',
    familyNumeric: '"Roboto Mono", "SFMono-Regular", Consolas, monospace',
    nativeFamily: {
      regular: 'Inter-Regular',
      medium: 'Inter-Medium',
      semibold: 'Inter-SemiBold',
      bold: 'Inter-Bold',
      numeric: 'RobotoMono-Regular',
      numericMedium: 'RobotoMono-Medium',
    },
    size: {
      xs: 11,
      sm: 13,
      md: 15,
      lg: 18,
      xl: 24,
      hero: 34,
    },
    lineHeight: {
      tight: 1.2,
      normal: 1.4,
      relaxed: 1.5,
      loose: 1.6,
    },
    weight: {
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
  },
  stateLayer: {
    hover: 0.08,
    focus: 0.1,
    pressed: 0.12,
    dragged: 0.16,
    disabled: 0.38,
  },
  motion: {
    instant: 80,
    fast: 140,
    normal: 200,
    emphasized: 260,
    slow: 320,
  },
  icon: {
    xs: 16,
    sm: 18,
    md: 20,
    lg: 24,
    xl: 28,
  },
  size: {
    minTouch: 48,
    rowCompact: 56,
    row: 64,
    rowLarge: 72,
    appbar: 64,
    bottomBar: 72,
  },
  density: {
    compact: 0.88,
    comfortable: 1,
    expanded: 1.12,
  },
  elevation: {
    level0: 0,
    level1: 1,
    level2: 2,
    level3: 3,
    level4: 4,
    level5: 5,
  },
} as const;

export type Tokens = typeof tokens;
export type MaterialThemeMode = keyof typeof tokens.color.md3;
